policy_path: "/home/ps/lpl/MoRE/logs/ym1_16dof_resi_moe/Jan20_16-45-47_/exported/policy_resi_1.pt"
xml_path: "/home/ps/lpl/MoRE/resources/robots/ym1/stairs.xml"


# Depth Camera
depth_far_clip: 2
depth_near_clip: 0
depth_buffer_len: 10
depth_size: [64, 64]
cam_update_interval: 5

# Camera randomization
crop_image: True
crop_size: [10, 20, 10, 2]  # left, top, right, bottom

gaussian_filter: False
gaussian_filter_kernel: 5
gaussian_filter_sigma: 1.5

gaussian_noise: False
gaussian_noise_std: 0.05

depth_dis_noise: 0


# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40, 60, 40, 60, 40]
kds: [3, 3, 3, 5, 2.5, 2.5, 3, 3, 3, 5, 2.5, 2.5, 2, 1, 2, 1]

default_angles: [-0.1, 0.0, 0.0, 0.35, -0.25, 0.0,
                 -0.1, 0.0, 0.0, 0.35, -0.25, 0.0,
                 0.46, 0.33, 0.46, 0.33]

init_qpos: [1, 0, 0, 0,
            -0.1, 0.0, 0.0, 0.35, -0.25, 0.0,
            -0.1, 0.0, 0.0, 0.35, -0.25, 0.0,
            0.46, 0.33, 0.46, 0.33]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 16
num_obs: 60
obs_history_len: 10

cmd_init: [1.0, 0, 0]
gait_cmd: [1, 0, 0]